language: go
go:
- 1.6
script:
- openssl aes-256-cbc -K $encrypted_4b931bee4503_key -iv $encrypted_4b931bee4503_iv
  -in service-account-key.json.enc -out service-account-key.json -d
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- curl https://sdk.cloud.google.com | bash
- /home/travis/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file service-account-key.json
- export APP_VERSION=$(git describe | tr '.' '-')
- /home/travis/google-cloud-sdk/bin/gcloud --project=organic-tree-151311 beta app deploy --version=$APP_VERSION --no-promote app/app.yaml
